# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the Node.js image as the base
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY src ./src

# Copy the tsconfig
COPY tsconfig.json ./

# Build the server
RUN npm run build

# Install Netlify CLI globally
RUN npm install -g netlify-cli

# Create a new stage for the runtime
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy build files from the builder stage
COPY --from=builder /app/build /app/build

# Copy node_modules from the builder stage
COPY --from=builder /app/node_modules /app/node_modules

# Copy package files
COPY package.json package-lock.json ./

# Set the entry point to run the server
ENTRYPOINT ["node", "build/index.js"]
